# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseAuth
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Facebook'
  
end
